name: Lightning Mailing list
on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: | 
          cd mailing-list && yarn
          cd ../common && yarn
      - name: Fetch data
        run: |
          mkdir /tmp/data
          cd mailing-list && node main.js
        env:
            ES_ENGINE: ${{ secrets.ES_ENGINE }}
            ES_URL: ${{ secrets.ES_URL }}
            ES_TOKEN: ${{ secrets.ES_TOKEN }}
            CLOUD_ID: ${{ secrets.CLOUD_ID }}
            USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
            USERNAME: ${{ secrets.USERNAME }}
            INDEX: ${{ secrets.INDEX }}
            DATA_DIR: /tmp/data
            URL: https://lists.linuxfoundation.org/pipermail/lightning-dev/
            NAME: lightning
            START_MONTH: 5
            START_YEAR: 2015
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            OPENAI_EMBED_MODEL: ${{ secrets.OPENAI_EMBED_MODEL }}
            CHUNK_SIZE: ${{ secrets.CHUNK_SIZE }}
            VECTORSTORE_INDEX: ${{ secrets.VECTORSTORE_INDEX }}
            ES_VECTORSTORE_INDEX: ${{ secrets.ES_VECTORSTORE_INDEX }}
